"""empty message

Revision ID: ad61d2f5abee
Revises: e1a8be4c9a05
Create Date: 2019-09-23 13:07:45.761942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad61d2f5abee'
down_revision = 'e1a8be4c9a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('priority', sa.Integer(), nullable=True))
    op.drop_column('banner', 'priorty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banner', sa.Column('priorty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('banner', 'priority')
    # ### end Alembic commands ###
